name: CD
on:
  workflow_run:
    workflows: ["CI"]
    types:
      - completed

jobs:
  train-deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    environment: sentiment_env
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Login to HuggingFace Hub
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          hf auth login --token "$HF_TOKEN" --add-to-git-credential

      - name: Train & push
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          python -m src.train --epochs 4 --push

      - name: Inference & log
        run: python -m src.infer --batch test --sample 100

      - name: Generate monitoring report
        run: python -m src.generate_report

      - uses: actions/upload-artifact@v4
        with:
          name: monitoring_report
          path: |
            report.txt
            report_distribuzione_classi.png
            report_distribuzione_confidence.png

