name: CD
on:
  workflow_run:
    workflows: ["CI"]
    types:
      - completed

jobs:
  train-deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    environment: sentiment_env
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - run: pip install -r requirements.txt

      - name: Login to HuggingFace Hub
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          hf auth login --token "$HF_TOKEN" --add-to-git-credential

      - name: Train & push
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          python src/train.py --epochs 10 --push
