name: CI
on: [push, pull_request]

jobs:
  lint-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - run: pip install -r requirements.txt

      # Lint
      - run: black --check .
      - run: isort --check .
      - run: flake8

      # Test
      - run: pytest -q
